ex_compile: ex_compile.c
	gcc `pkg-config --cflags glib-2.0` ex_compile.c -o ex_compile `pkg-config --libs glib-2.0`

word_count: word_count.c
	gcc `pkg-config --cflags glib-2.0` word_count.c -o word_count `pkg-config --libs glib-2.0`